verbose: false
instrumentation:
    root: .
    include-all-sources: true
    excludes: ['spec/**', 'doc/build/**', 'jsdoc_build/**']
    default-excludes: true
reporting:
    print: detail
    reports:
        - lcov
        - html
    dir: ./cover
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
    each:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
