- job:
    name: nodejs-npm4-run-docs
    parent: nodejs-npm
    vars:
      npm_command: docs
      node_version: 4

- job:
    name: nodejs-npm6-run-docs
    parent: nodejs-npm
    vars:
      npm_command: docs
      node_version: 6

- job:
    name: nodejs-npm4-run-functional-test
    parent: nodejs-npm
    vars:
      npm_command: functional-test
      node_version: 4

- job:
    name: nodejs-npm6-run-functional-test
    parent: nodejs-npm
    vars:
      npm_command: functional-test
      node_version: 6

- project:
    name: openstack-infra/js-generator-openstack

    check:
      jobs:
        - nodejs-npm6-run-docs
